<#
.SYNOPSIS
    Packages the complete source tree into one archive that can be handed to another
    machine or agent and rebuilt from scratch.

.DESCRIPTION
    The archive carries every source file the project needs — frontend, Rust backend,
    installer and uninstaller sources, Tauri configuration, icons, build/verify scripts,
    dependency manifests and lock files, README and the git history — and nothing that can
    be regenerated: node_modules, Rust target, dist, the assembled release folder, caches,
    logs and temporary test output.

    The payload/runtime binaries are deliberately absent: FFmpeg and yt-dlp are an external
    runtime (E:\FFMPEG-9.0 during development) that the build copies into the release, and
    the installer payload is generated from that release folder.

.PARAMETER OutputPath
    Target .zip. Defaults to <workspace>\YTDownloader-source-<version>-<yyyyMMdd>.zip.

.PARAMETER IncludeGit
    Include the .git directory (history and remote configuration). On by default.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File scripts\package-source.ps1
#>

[CmdletBinding()]
param(
    [string] $OutputPath,
    [switch] $IncludeGit = $true
)

$ErrorActionPreference = 'Continue'
Set-StrictMode -Version Latest

$ProjectRoot = Split-Path -Parent $PSScriptRoot
$Workspace = Split-Path -Parent $ProjectRoot

$packageJson = Get-Content (Join-Path $ProjectRoot 'package.json') -Raw | ConvertFrom-Json
$version = $packageJson.version
if (-not $OutputPath) {
    $stamp = Get-Date -Format 'yyyyMMdd'
    $OutputPath = Join-Path $Workspace "YTDownloader-source-$version-$stamp.zip"
}

# Directories that are regenerated by installing dependencies or building.
$excludedDirectories = @('node_modules', 'target', 'dist', 'release', 'data', '.caches', '.ui-profile', '.git')
if ($IncludeGit) {
    $excludedDirectories = $excludedDirectories | Where-Object { $_ -ne '.git' }
}

Write-Host ''
Write-Host 'YT Downloader — 源码打包' -ForegroundColor Cyan
Write-Host "  项目 : $ProjectRoot"
Write-Host "  版本 : $version"
Write-Host "  输出 : $OutputPath"
Write-Host ''

# ------------------------------------------------------------------ collect
$all = Get-ChildItem $ProjectRoot -Recurse -File -Force | Where-Object {
    $relative = $_.FullName.Substring($ProjectRoot.Length + 1)
    $segments = $relative.Split('\')
    $blocked = $false
    # A directory is excluded wherever it appears, but only as a whole path segment:
    # `src-tauri/src/runtime` is source code, `runtime/` at the root is the FFmpeg copy.
    foreach ($segment in $segments[0..([Math]::Max(0, $segments.Count - 2))]) {
        if ($excludedDirectories -contains $segment) { $blocked = $true }
    }
    if ($blocked) { return $false }
    if ($_.Name -match '\.(log|tmp|part|zip)$') { return $false }
    if ($_.Name -in @('Thumbs.db', 'desktop.ini', '.DS_Store')) { return $false }
    return $true
}

$totalBytes = ($all | Measure-Object Length -Sum).Sum
Write-Host "  文件数 : $($all.Count)"
Write-Host ("  大小   : {0:N2} MB" -f ($totalBytes / 1MB))

# -------------------------------------------------------------------- write
# Windows PowerShell 5.1 needs both assemblies loaded explicitly: the ZipArchive types
# live in System.IO.Compression, the factory helpers in System.IO.Compression.FileSystem.
Add-Type -AssemblyName System.IO.Compression | Out-Null
Add-Type -AssemblyName System.IO.Compression.FileSystem | Out-Null
if (Test-Path $OutputPath) { Remove-Item $OutputPath -Force }

$stream = [System.IO.File]::Open($OutputPath, [System.IO.FileMode]::CreateNew)
$archive = New-Object System.IO.Compression.ZipArchive($stream, [System.IO.Compression.ZipArchiveMode]::Create)
try {
    foreach ($file in $all) {
        $entryName = $file.FullName.Substring($ProjectRoot.Length + 1).Replace('\', '/')
        [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile(
            $archive, $file.FullName, $entryName, [System.IO.Compression.CompressionLevel]::Optimal) | Out-Null
    }
}
finally {
    $archive.Dispose()
    $stream.Dispose()
}

# ------------------------------------------------------------------- verify
$zipInfo = Get-Item $OutputPath
Write-Host ''
Write-Host '校验压缩包…' -ForegroundColor Cyan
Write-Host ("  压缩包 : {0:N2} MB" -f ($zipInfo.Length / 1MB))

$readArchive = [System.IO.Compression.ZipFile]::OpenRead($OutputPath)
$names = @()
try {
    # Strict mode requires the variable to exist even when the enumeration is empty.
    $names = @($readArchive.Entries | ForEach-Object { $_.FullName })
}
finally {
    $readArchive.Dispose()
}
Write-Host "  条目数 : $($names.Count)"

$failures = @()

function Check([bool] $Condition, [string] $Message) {
    if ($Condition) { Write-Host "  ok   $Message" -ForegroundColor Green }
    else { Write-Host "  FAIL $Message" -ForegroundColor Red; $script:failures += $Message }
}

# The installer and the uninstaller live in two places: the Tauri crate and the shared
# frontend. Both must be inside the archive or the project can no longer be rebuilt.
$required = @(
    'package.json',
    'package-lock.json',
    'vite.config.ts',
    'tsconfig.json',
    'tsconfig.node.json',
    'index.html',
    'installer.html',
    'README.md',
    'src/installer/main.tsx',
    'src/installer/InstallerApp.tsx',
    'src/installer/pages/OptionsPage.tsx',
    'src/installer/pages/ProgressPage.tsx',
    'src/installer/pages/DonePage.tsx',
    'src/installer/pages/UninstallPage.tsx',
    'src/installer/components/SetupFrame.tsx',
    'src-setup/Cargo.toml',
    'src-setup/Cargo.lock',
    'src-setup/tauri.conf.json',
    'src-setup/build.rs',
    'src-setup/src/install.rs',
    'src-setup/src/uninstall.rs',
    'src-setup/src/payload.rs',
    'src-setup/src/platform.rs',
    'src-setup/src/cli.rs',
    'src-setup/src/commands.rs',
    'src-setup/src/progress.rs',
    'src-setup/src/lib.rs',
    'src-setup/icons/icon.ico',
    'src-tauri/Cargo.toml',
    'src-tauri/Cargo.lock',
    'src-tauri/tauri.conf.json',
    'src-tauri/src/lib.rs',
    'src-tauri/src/core/fs_util.rs',
    'src-tauri/tests/integration.rs',
    'scripts/build.ps1',
    'scripts/dev-env.ps1',
    'scripts/make_payload.py',
    'scripts/verify-installer.ps1',
    'scripts/verify-release.mjs',
    'scripts/e2e-youtube.mjs'
)
$missing = @($required | Where-Object { $names -notcontains $_ })
$missingText = if ($missing.Count) { $missing -join ', ' } else { '无' }
Check ($missing.Count -eq 0) "关键源码文件齐全（缺失：$missingText）"

$forbidden = @('node_modules/', '/target/', 'dist/', 'release/', '/.caches/', '.log')
$found = @($names | Where-Object { $name = $_; $forbidden | Where-Object { $name -like "*$_*" } })
$foundText = if ($found.Count) { ($found | Select-Object -First 3) -join ', ' } else { '无' }
Check ($found.Count -eq 0) "不含构建产物与缓存（命中：$foundText）"

Check ($names -contains 'scripts/verify-reveal.ps1') "包含定位功能验证脚本"
Check ($names -contains 'scripts/verify-installer-ui.mjs') "包含安装器/卸载器界面验证脚本"
Check ($names -contains 'scripts/package-source.ps1') "包含源码打包脚本自身"
if ($IncludeGit) {
    Check (($names | Where-Object { $_ -like '.git/*' }).Count -gt 0) "包含 .git 历史（便于后续维护）"
}

Write-Host ''
if ($failures.Count -gt 0) {
    Write-Host "源码打包校验失败 $($failures.Count) 项。" -ForegroundColor Red
    exit 1
}

Write-Host "源码包已生成：$OutputPath" -ForegroundColor Green
Write-Host ("  条目数 : {0}" -f $names.Count)
exit 0
